forum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum_body.urls')), # forum pages
    path('user/', include('users.urls')), # user pages
]

forum_body/urls.py
"""Код обьявлений urls для forum_body"""

from django.urls import path
from . import views

app_name = 'forum_body'
urlpatterns = [
        path('', views.index, name='index'), # homepage
        path('<str:topic_name>/', views.topic, name='topic'), # topic page
        path('<str:topic_name>/<int:discussion_id>/', views.discussion, name='discussion'), # topic discussion page
        path('edit/<str:topic_name>/<int:discussion_id>/<int:message_id>/', views.message_edit, name='message_edit'), # message edit page
        path('new_topic/>', views.new_topic, name='new_topic'), # topic creation page
        path('<str:topic_name>/new_discussion/', views.new_discussion, name='new_discussion'), # discussion creation page
        path('delete_message/<int:topic_id>/<int:discussion_id>/<int:message_id>', views.delete_message, name='delete_message'), # message delete function
        ]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
        path('', include('django.contrib.auth.urls')),
        path('register/', views.register, name='register'),
        ]

forum_body/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """Discussion"""

    name = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.name

class Discuss(models.Model):
    """Branch of discussion"""

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    head = models.CharField(max_length=100)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.head

class Messages(models.Model):
    """Message in branch of discussion"""

    discuss = models.ForeignKey(Discuss, on_delete=models.CASCADE) 
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=20000)

forum_body/forms.py
from django import forms
from .models import Messages, Topic, Discuss

class MessageForm(forms.ModelForm):
    class Meta:
        model = Messages
        fields = ['owner', 'text']
        labels = {'owner': '', 'text':''}
        widgets = {
                'owner': forms.HiddenInput(),
                'text': forms.Textarea(attrs={
                    'cols':120,
                    'maxlength':20000,
                    'style':'resize:none',
                    })
                }

class EditForm(forms.ModelForm):
    """Message editing form"""

    class Meta:
        model = Messages
        fields = [ 'text']
        labels = {'text':'Redact message'}
        widgets = {
                'text': forms.Textarea(attrs={
                    'cols':120,
                    'maxlength':20000,
                    'style':'resize:none',
                    })
                }

class TopicAddForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['name']  
        labels = {'name': 'Type new topic name:'}
        widgets = {'name': forms.Textarea(attrs={
            'style': 'resize:none',
            'cols': 120,
            'rows':1})}       

class NewDiscussionForm(forms.ModelForm):
    class Meta:
        model = Discuss
        fields = ['head']
        labels = {'head': 'Enter a discussion name'}
        widgets = {'head': forms.Textarea(attrs={
            'style': 'resize:none',
            'cols': 120,
            'rows':1,})}

forum_body/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Topic, Discuss, Messages
from .forms import MessageForm, EditForm, TopicAddForm, NewDiscussionForm
from django.contrib.auth.decorators import login_required
from django.http import Http404

# Help functions

def check_user_ownership(request, place):
    """Compares user and place owner ids, if it different, raises a 404 error"""

    if place.owner.id != request.user.id:
        raise Http404

# Create your views here.

def index(request):
    """Renders homepage"""

    topics = Topic.objects.all()
    context = {'topics':topics}

    return render(request, 'forum_body/index.html', context)

def topic(request, topic_name):
    """Renders topic page"""
    
    topic = get_object_or_404(Topic, name=topic_name)
    discussions = topic.discuss_set.all()
    discussion = Discuss.objects.all()
    context = {
            'topic':topic, 'topic_name':topic.name, 'discussions':discussions,
            'discussion':discussion, 
            }

    return render(request, 'forum_body/topic.html', context)


def discussion(request, topic_name, discussion_id):
    """Renders discussion page and implements message creation form"""

    topic = get_object_or_404(Topic, name=topic_name)
    discussion = get_object_or_404(Discuss, id=discussion_id) 
    messages = discussion.messages_set.all()
    
    # message creation form
    if request.method != 'POST':
        message_form = MessageForm()
    else:
        message_form = MessageForm(data=request.POST)
        if message_form.is_valid():
            new_message = message_form.save(commit=False)
            new_message.topic = topic
            new_message.discuss = discussion
            new_message.save()
            return redirect('forum_body:discussion', topic_name=topic_name, discussion_id=discussion_id)

    context = {'topic':topic, 'discussion':discussion, 'messages':messages,
                'form':message_form}

    return render(request, 'forum_body/discussion.html', context)
    
@login_required
def message_edit(request, topic_name, discussion_id, message_id):
    """Renders message edit page"""

    topic = get_object_or_404(Topic, name=topic_name)
    discussion = get_object_or_404(Discuss, id=discussion_id)
    message = get_object_or_404(Messages, id=message_id)
    check_user_ownership(request, message)

    if request.method != 'POST':
        edit_form = EditForm(instance=message)
    else:
        edit_form = EditForm(instance=message, data=request.POST)
        if edit_form.is_valid():
            edit_form.save()
            return redirect('forum_body:discussion',
                    topic_name=topic.name, discussion_id=discussion.id)
        
    context = {'discussion': discussion, 'message': message, 'form':edit_form, 'topic':topic}
    return render(request, 'forum_body/edit_message.html', context)

@login_required
def new_topic(request):
    """Renders message creation page"""
    
    if request.method != 'POST':
        topic_add_form = TopicAddForm()
    else:   
        topic_add_form = TopicAddForm(data=request.POST)
        if topic_add_form.is_valid():
            topic_add_form.save()
            return redirect('forum_body:index')
    context = {'form': topic_add_form}
    return render(request, 'forum_body/add_topic.html', context)

@login_required
def new_discussion(request, topic_name):
    """Renders discussion creation page"""

    topic = get_object_or_404(Topic, name=topic_name)

    if request.method != 'POST':
        new_discussion_form = NewDiscussionForm()
    else:
        new_discussion_form = NewDiscussionForm(data=request.POST)
        if new_discussion_form.is_valid():
            new_form = new_discussion_form.save(commit=False)
            new_form.topic = topic
            new_form.save()
            return redirect('forum_body:topic', topic_name = topic_name)
    context = {'form':new_discussion_form, 'topic': topic}
    return render(request, 'forum_body/new_discussion.html', context)

def delete_message(request,topic_id, discussion_id, message_id):
    """Deletes message from discussion page and db"""

    topic = get_object_or_404(Topic, id=topic_id)
    discussion = get_object_or_404(Discuss, id=discussion_id)
    message = get_object_or_404(Messages, id=message_id)
    check_user_ownership(request, message)
    
    message.delete()
    return redirect('forum_body:discussion', topic_name=topic.name, discussion_id=discussion.id)

forum_body/templates/forum_body/add_topic.html
{% extends 'forum_body/base.html' %}

{% block title %}
	- add topic
{% endblock %}

{% block content %}
	<h2 align=Center>Add topic</h2>
	<hr>
	<form method='POST' action="{% url 'forum_body:new_topic' %}">
		{% csrf_token %}
		{{ form.as_p }}
		<button name='submit'>Add topic</button>
	</form>
{% endblock %}

forum_body/templates/forum_body/base.html
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<doctype html>

<html>
	<head>		<meta charset="utf-8">
		<meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>


		<title>
			Forum 4all {% block title %} {% endblock title %}
		</title>
		</head>

	<body>
			<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
				<a class="navbar-brand" href="{%url 'forum_body:index' %} ">
					Forum 4all
				</a>
  			<button class="navbar-toggler" type="button"
				data-toggle="collapse" data-target="#navbarSupportedContent"
				aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
    				<span class="navbar-toggler-icon"></span>
  			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
   				<ul class='navbar nav ml-auto'>
		  			{% if user.is_authenticated %}
					<li class='navbar-item ml-auto active'>
						<span class='navbar-text'>
							Hello, {{ user.username }}
						</span> 
					</li>
					<li class='navbar-item ml-auto'>
		   				<a href="{% url 'users:logout' %}" 
						class='nav-item mr-auto nav-link'>
							Log out
						</a>
					</li>
					{% else %}
						<li class='navbar-item ml-auto me-auto'>
						<a href="{% url 'users:login' %}" 
						class='nav-item nav-link mr-auto pd-auto'>
							Login in
						</a> 
					</li>
					<li class='navbar-item ml-auto'>
			   			<a href="{% url 'users:register' %}"
						class='nav-item nav-link mr-auto pd-auto'>
							Registration
						</a>
					</li>
				</ul>
					{% endif %}
			</div>
			</nav>
		<main role='main' class='container'>
			<div class='mt-2 pt-2 mb-2 pb-2 border-bottom'>	
				{% block page_header %}
				{% endblock page_header %}
			</div>
			<div>
				{% block content %}
				{% endblock content %}	
			</div>
		</main>

	</body>
</html>

forum_body/templates/forum_body/discussion.html
{% extends 'forum_body/base.html' %}
{% load bootstrap4 %}

{% block title %}
	- {{ discussion.head }}
{% endblock %}

{% block page_header %}
	<h2 class='text-center'>{{ discussion.head }}</h2>
{% endblock page_header %}

{% block content %}
		{% for message in messages %}
	<div class='card mb-4'>
			<h5 class='card-header'>
				{{ message.owner.username }}. {{ message.date_added }} <small>
				{% if user.id == message.owner.id %}	
					<a href="{% url 'forum_body:delete_message' topic.id discussion.id message.id %}"
				   		class='btn btn-primary float-right '>
					Delete
					</a>
					<a href="{% url 'forum_body:message_edit' topic.name discussion.id message.id %}"
				  	 	class='btn btn-primary float-right mr-3'>
						Edit
					</a>
					{% endif %}</small>
			</h5>
		<div class='card-body'>
			{{ message.text|linebreaks }}
		</div>

	</div>
		{% empty %}
			<p class='card-header'>There's no comments, be first!</p>
		{% endfor %}
	<hr>
	{% if user.is_authenticated %}
	<p>Enter  message:</p>
		<form action='' method='POST' class='form'>
			{% csrf_token %}
			{% bootstrap_form form %}
			{% buttons %}
			<button name='submit' class='btn btn-primary'>Enter</button>
			{% endbuttons %}

			<input type='hidden' value='{{user.id}}' name='owner' />
		</form>
	{% else %}
		<p class='card-header'>Login in to comment discussion</p>
	{% endif %}
{% endblock %}

forum_body/templates/forum_body/edit_message.html
{% extends 'forum_body/base.html' %}

{% block title %}
	- edit 
{% endblock %}

{% block content %}
	<h2 align=Center> Editting: {{ discussion.head }} message </h2>
	<hr>
	<form action="{% url 'forum_body:message_edit' topic.name discussion.id message.id %}" method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name='submit'>Enter</button>
	</form>
{% endblock %}

forum_body/templates/forum_body/index.html
{% extends "forum_body/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
	<div class='jumbotron'>
		<h1 class='display-8'>Welcome to Forum 4all!</h1>
		<p class='lead'>
			This is a place, where you can talk about almost everything with unknown people or with your friends. 
		</p>
	</div>
{% endblock page_header %}

{% block content %}
	<h2 align=Center>Topics</h2>
	{% if user.is_authenticated %}
		<a href="{% url 'forum_body:new_topic' %}"
	   	   class='btn btn-primary mb-4'>
			Add topic
		</a>
	{% else %}
		<p class='btn btn-primary mb-4'>Login to create new topics</p>
	{% endif %}
	{% for topic in topics %}
		<div class='card mb-2'>
			<a href="{% url 'forum_body:topic' topic.name %}"
			   class='card-header'>
				{{ topic.name }}
			</a>
		</div>
	{% empty %}
			<p class='card-header'>There's no topics, but you can create your own!</p>
	{% endfor %}
{% endblock %}

forum_body/templates/forum_body/new_discussion.html
{% extends 'forum_body/base.html' %}

{% block title %}
	- new discussion
{% endblock %}

{% block content %}
	<h2 align=Center>New discussion</h2>
	<hr>
	<form action='{% url "forum_body:new_discussion" topic.name %}' method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<button name='submit'>Enter</button>
	</form>
{% endblock %}

forum_body/templates/forum_body/topic.html
{% extends 'forum_body/base.html' %}
{% load bootstrap4 %}

{% block title %}
	- {{topic_name}}
{% endblock %}

{% block content %}
		<h2 align=Center>Choose discussion</h2>
		{% if user.is_authenticated %}
		<a href='{% url 'forum_body:new_discussion' topic.name %}'
		  class='btn btn-primary mb-2'>
			Add new discussion
		</a>
	{% else %}
		<p class='btn btn-primary'>Login in to add new discussions</p>
	{% endif %}
		{% for discussion in discussions %}
	<div class='card mb-3'> 
			<a href="{% url 'forum_body:discussion' topic.name discussion.id %}"
			class='card-header'>
			      {{ discussion.head }}
			</a>
	</div>
		{% endfor %}
{% endblock %}